[package]
name = "ixa-epi-covid"
version = "0.1.0"
edition = "2024"
default-run = "ixa-epi-covid"

[lib]
name = "epimodel"
crate-type = ["cdylib", "rlib"]

[lib]
name = "epimodel"
crate-type = ["cdylib", "rlib"]

[dependencies]
ixa = "0.5.0"
serde = "1.0.217"
serde_json = "1.0.139"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true

[lints.rust]
#turn all rsutc warnings into errors
warnings = "deny"

[lints.clippy]
module_name_repetitions = "allow"
match_wildcard_for_single_variants = "allow"
uninlined_format_args = "allow"
