input = "/app/default_params.json"

[model]
spec = "ixa_epi_covid_phase1"
version = "0.1.0"

[runtime]
spec = "process"
command = "/app/.venv/bin/python"
args = [
  "-m",
  "ixa_epi_covid.mrp_task_runner",
]

[output]
spec = "filesystem"
dir = "./output"
