input = "experiments/phase1/input/default_params.json"

[model]
spec = "ixa_epi_covid_phase1"
version = "0.1.0"

[runtime]
spec = "inline"
callable = "ixa_epi_covid.cloud.mrp_executor:execute_cloud_run"

[runtime.cloud]
keyvault = "cfa-predict"
local_image = "ixa-epi-covid-cloud"
repository = "ixa-epi-covid-cloud"
task_mrp_config_path = "/app/ixa_epi_covid.mrp.task.toml"
pool_prefix = "ixa-epi-covid-cloud"
job_prefix = "ixa-epi-covid-cloud"
input_container_prefix = "ixa-epi-covid-cloud-input"
output_container_prefix = "ixa-epi-covid-cloud-output"
logs_container_prefix = "ixa-epi-covid-cloud-logs"
input_mount_path = "/cloud-input"
output_mount_path = "/cloud-output"
logs_mount_path = "/cloud-logs"
vm_size = "large"
jobs_per_session = 1
task_slots_per_node = 50
pool_max_nodes = 5
task_timeout_minutes = 60
pool_ready_timeout_minutes = 20
pool_auto_scale_evaluation_interval_minutes = 5
dispatch_buffer = 1000
print_task_durations = false

[output]
spec = "filesystem"
dir = "./output"
