[project]
name = "ixa-epi-covid"
version = "0.1.0"
description = "Epidemiological models for COVID-19 developed in ixa"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "maturin>=1.11.5",
    "numpy>=2.3.4",
    "pyarrow>=23.0.0",
    "pytest>=9.0.2",
    "scipy>=1.16.3",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.uv]
package = false
